---
driver:
  name: docker
  #run_command: /usr/sbin/sshd -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid; /sbin/init
  privileged: true

provisioner:
  name: chef_solo
  roles_path: provision/chef/roles
  data_bags_path:  provision/chef/data_bags
  cookbook_path:
    - provision/chef/cookbooks
    - provision/chef/vendor-cookbooks

platforms:
  - name: centos-7
    driver_config:
      image: 2k0ri/centos7-systemd
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu-upstart:14.04
      run_command: /sbin/init
      disable_upstart: false

suites:
  - name: mysql
    includes:
      - centos-7
      - ubuntu-14.04
    run_list:
      - role[mysql]

  - name: jenkins
    includes:
      - centos-7
      - ubuntu-14.04
    run_list:
      - role[jenkinsonar]
    attributes:
      jenkins-job:
        job-templates:
          test_sonar: test_sonar.xml.erb

  - name: flamegraph
    includes:
      - centos-7
      - ubuntu-14.04
    run_list:
      - role[flamegraph]

  - name: headless
    includes:
      - centos-7
      - ubuntu-14.04
    run_list:
      - role[opspipeline-headless]

  - name: desktop
    includes:
      - ubuntu-14.04
    run_list:
      - role[opspipeline-desktop]
