---
rvm: 2.2

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

env:
  fast_finish: true

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --auto-gen-config
  - cat .rubocop_todo.yml
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic provision/chef/cookbooks/
#  - kitchen test
#  - KITCHEN_LOCAL_YAML=.kitchen.system.yml kitchen verify ${INSTANCE}

after_script:
  # - docker images
  # - docker ps -a
  - cat .kitchen/logs/kitchen.log
